/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { RouterHistory } from "@stencil/router";
export namespace Components {
    interface AppDetails {
        "elementID": string;
        "history": RouterHistory;
        "media_type": string;
    }
    interface AppMain {
        "showMore": (amount: number) => Promise<void>;
    }
    interface AppMovies {
    }
    interface AppRoot {
    }
    interface AppTvshows {
    }
    interface DefaultCard {
        "history": RouterHistory;
        "item": any;
    }
    interface FeaturedCard {
        "elementId": string;
        "goTo": (e: any, route: any, data: any) => Promise<void>;
        "history": RouterHistory;
        "mediaType": string;
    }
    interface MainFooter {
    }
    interface TypeaheadSearch {
        "getSearchResult": (term: string) => Promise<void>;
        "goTo": (e: any, route: any, data: any) => Promise<void>;
        "history": RouterHistory;
        "onSearchInput": (val: string) => Promise<void>;
    }
}
declare global {
    interface HTMLAppDetailsElement extends Components.AppDetails, HTMLStencilElement {
    }
    var HTMLAppDetailsElement: {
        prototype: HTMLAppDetailsElement;
        new (): HTMLAppDetailsElement;
    };
    interface HTMLAppMainElement extends Components.AppMain, HTMLStencilElement {
    }
    var HTMLAppMainElement: {
        prototype: HTMLAppMainElement;
        new (): HTMLAppMainElement;
    };
    interface HTMLAppMoviesElement extends Components.AppMovies, HTMLStencilElement {
    }
    var HTMLAppMoviesElement: {
        prototype: HTMLAppMoviesElement;
        new (): HTMLAppMoviesElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppTvshowsElement extends Components.AppTvshows, HTMLStencilElement {
    }
    var HTMLAppTvshowsElement: {
        prototype: HTMLAppTvshowsElement;
        new (): HTMLAppTvshowsElement;
    };
    interface HTMLDefaultCardElement extends Components.DefaultCard, HTMLStencilElement {
    }
    var HTMLDefaultCardElement: {
        prototype: HTMLDefaultCardElement;
        new (): HTMLDefaultCardElement;
    };
    interface HTMLFeaturedCardElement extends Components.FeaturedCard, HTMLStencilElement {
    }
    var HTMLFeaturedCardElement: {
        prototype: HTMLFeaturedCardElement;
        new (): HTMLFeaturedCardElement;
    };
    interface HTMLMainFooterElement extends Components.MainFooter, HTMLStencilElement {
    }
    var HTMLMainFooterElement: {
        prototype: HTMLMainFooterElement;
        new (): HTMLMainFooterElement;
    };
    interface HTMLTypeaheadSearchElement extends Components.TypeaheadSearch, HTMLStencilElement {
    }
    var HTMLTypeaheadSearchElement: {
        prototype: HTMLTypeaheadSearchElement;
        new (): HTMLTypeaheadSearchElement;
    };
    interface HTMLElementTagNameMap {
        "app-details": HTMLAppDetailsElement;
        "app-main": HTMLAppMainElement;
        "app-movies": HTMLAppMoviesElement;
        "app-root": HTMLAppRootElement;
        "app-tvshows": HTMLAppTvshowsElement;
        "default-card": HTMLDefaultCardElement;
        "featured-card": HTMLFeaturedCardElement;
        "main-footer": HTMLMainFooterElement;
        "typeahead-search": HTMLTypeaheadSearchElement;
    }
}
declare namespace LocalJSX {
    interface AppDetails {
        "elementID"?: string;
        "history"?: RouterHistory;
        "media_type"?: string;
    }
    interface AppMain {
    }
    interface AppMovies {
    }
    interface AppRoot {
    }
    interface AppTvshows {
    }
    interface DefaultCard {
        "history"?: RouterHistory;
        "item"?: any;
    }
    interface FeaturedCard {
        "elementId"?: string;
        "history"?: RouterHistory;
        "mediaType"?: string;
    }
    interface MainFooter {
    }
    interface TypeaheadSearch {
        "history"?: RouterHistory;
    }
    interface IntrinsicElements {
        "app-details": AppDetails;
        "app-main": AppMain;
        "app-movies": AppMovies;
        "app-root": AppRoot;
        "app-tvshows": AppTvshows;
        "default-card": DefaultCard;
        "featured-card": FeaturedCard;
        "main-footer": MainFooter;
        "typeahead-search": TypeaheadSearch;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-details": LocalJSX.AppDetails & JSXBase.HTMLAttributes<HTMLAppDetailsElement>;
            "app-main": LocalJSX.AppMain & JSXBase.HTMLAttributes<HTMLAppMainElement>;
            "app-movies": LocalJSX.AppMovies & JSXBase.HTMLAttributes<HTMLAppMoviesElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-tvshows": LocalJSX.AppTvshows & JSXBase.HTMLAttributes<HTMLAppTvshowsElement>;
            "default-card": LocalJSX.DefaultCard & JSXBase.HTMLAttributes<HTMLDefaultCardElement>;
            "featured-card": LocalJSX.FeaturedCard & JSXBase.HTMLAttributes<HTMLFeaturedCardElement>;
            "main-footer": LocalJSX.MainFooter & JSXBase.HTMLAttributes<HTMLMainFooterElement>;
            "typeahead-search": LocalJSX.TypeaheadSearch & JSXBase.HTMLAttributes<HTMLTypeaheadSearchElement>;
        }
    }
}
